### ISSUE TITLE
Guide to README how to install manually

### ISSUE THREAD

**Issue by failattu** [Eficode/robotframework-imagehorizonlibrary#11]
As the code isn't available currently available in pip it would be great that the guide would be bit more detailed for non pip install name of the project.

Meaning following

git clone https://github.com/Eficode/robotframework-imagehorizonlibrary.git
cd robotframework-imagehorizonlibrary
pip install pillow
pip install .

**Comment by pajupaju** [comment]
Before ImageHorizon is added to PyPi, you need to install it manually:

    Download the package: https://github.com/Eficode/robotframework-imagehorizonlibrary/archive/master.zip
    Move to the desired installation folder and unpack downloaded ImageHorizon-package. Then run command:

    python setup.py sdist

    Move into extracted "robotframework-imagehorizonlibrary-master" folder and run command: pip install dist/ImageHorizonLibrary{version}.zip for example:

    pip install dist/ImageHorizonLibrary-0.1-devel.zip

    Take library to use at Robot Framework for example like this:

    Library           ImageHorizonLibrary    ${CURDIR}${/}${REF_IMAGE_FOLDER}    ${SCREENSHOT_FOLDER}    
    ...      keyword_on_failure=Screenshot.Take Screenshot

**Comment by suonto** [comment]
Changed the instructions until the package is added to PyPI.
