### ISSUE TITLE
Lacking a keyword, which returns current data from the clipboard

### ISSUE THREAD

**Issue by pajupaju** [Eficode/robotframework-imagehorizonlibrary#2]
Now "Copy" simply works: ctrl+c -> ctrl+v
Would be useful to be able to copy fields with some other keyboard combinations also, because random "copy to clipboard" -keyboard shortcuts are used at desktop apps for example.

**Comment by suonto** [comment]
Pushed to master in commit dbd165f28222c2de968702dc1e5c8cd6636aac8e
