### ISSUE TITLE
Error with "Copy From The Right Of"

### ISSUE THREAD

**Issue by vinaybond** [Eficode/robotframework-imagehorizonlibrary#22]
I am getting error:
Keyword 'ImageHorizonLibrary.Copy From The Right Of' expected 2 arguments, got 3.

This is the code
```
@{coordinates}=	Create List	${150}	${3}
ImageHorizonLibrary.Copy From The Right Of Image	LastCmdLable	@{coordinates}

```

same code is working for 
`ImageHorizonLibrary.Click To The Right Of Image	LastCmdLable  	@{coordinates}
`

Thanks

**Comment by Tattoo** [comment]
`Copy From The Right Of` does not take coordinates, as detailed in the documentation[1]. Neither does `Click To The Right Of Image`. What are you trying to do?

**Comment by vinaybond** [comment]
That was the typo about the syntax. Sorry for that. 

I am using Windows 7. Python 2.7.10

**Comment by vinaybond** [comment]
The syntax says it takes to argument

 reference_image | offset

offset = coordinates, right?

**Comment by Tattoo** [comment]
no, offset is offset. if you read the documentation, it will clearly point you to another keyword, which explains what offset is.
