### ISSUE TITLE
Image captured for google chrome does not work for firefox

### ISSUE THREAD

**Issue by vinaybond** [Eficode/robotframework-imagehorizonlibrary#24]
I have html5 canvas and I have captured small rectangle from it. It works fine google chrome (which I think I used to capture image) but firefox it does not. I tried checking the difference of shades, size etc but I could not see any difference in which component is being randered on canvas.

**Comment by Tattoo** [comment]
Sorry to say, but if the image is not being recognized, you unfortunately need to find some other way to deal with the situation -- I cannot really help
