### ISSUE TITLE
Installation with Python3 doesn't work

### ISSUE THREAD

**Issue by asimell** [eficode/robotframework-imagehorizonlibrary#25]
Trying to install with Python 3.x gives the following error message:

$ pip3 install robotframework-imagehorizonlibrary
Collecting robotframework-imagehorizonlibrary
  Using cached robotframework-imagehorizonlibrary-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hy/kt73qtfj3rvg6j_zzt0vjt4c0000gn/T/pip-build-9tqxbdjt/robotframework-imagehorizonlibrary/setup.py", line 8, in <module>
        execfile('src/ImageHorizonLibrary/version.py')
    NameError: name 'execfile' is not defined

**Comment by Tattoo** [comment]
`execfile()` was removed in Python 3: 

http://stackoverflow.com/questions/436198/what-is-an-alternative-to-execfile-in-python-3-0

**Comment by JonKoser** [comment]
Just to note - I have a working Python3 version of the library (along with some other fixes) here: https://github.com/JonKoser/robotframework-imagehorizonlibrary/tree/integration. The python3 conversion was done in my feature/python3 branch.

**Comment by davidk1** [comment]
Cannot install **robotframework-imagehorizonlibrary**.

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
robotframework 3.1.2

After execution of command: _pip install robotframework-imagehorizonlibrary_ I always get following error:

`
ERROR: Command errored out with exit status 1:
     command: 'c:\users\xyz\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xyz\\AppData\\Local\\Temp\\1\\pip-install-wpfqz4yq\\robotframework-imagehorizonlibrary\\setup.py'"'"'; __file__='"'"'C:\\Users\\xyz\\AppData\\Local\\Temp\\1\\pip-install-wpfqz4yq\\robotframework-imagehorizonlibrary\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\xyz\AppData\Local\Temp\1\pip-install-wpfqz4yq\robotframework-imagehorizonlibrary\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xyz\AppData\Local\Temp\1\pip-install-wpfqz4yq\robotframework-imagehorizonlibrary\setup.py", line 8, in <module>
        execfile('src/ImageHorizonLibrary/version.py')
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by JonKoser** [comment]
That makes sense - doesn't look like the new version is up on PyPi.

**Comment by davidk1** [comment]
Ok, can you please tell me when we can download new version from PyPi?

**Comment by JonKoser** [comment]
I can't really do that since it's not my codebase and I'm only a contributor, but there is a workaround until it gets updated. Open a terminal (run as administrator if on Windows) and:

1) Git clone this repository
2) `cd` into the robotframework-imagehorizonlibrary directory you just downloaded
3) Run `python3 setup.py build`
4) Run `sudo setup.py install` - can omit the `sudo` if on Windows

You should now be able to use the library.


Alternatively, you can also just download this repository and point PYTHONPATH at the "src" directory. Ex: `python3 -m robot --pythonpath=/path/to/robotframework-imagehorizonlibrary/src .`

**Comment by davidk1** [comment]
Thank you @JonKoser

**Comment by Tattoo** [comment]
fixed in #44 . Thanks @JonKoser !
