### ISSUE TITLE
Error while adding Horizonlibrary in Eclipse

### ISSUE THREAD

**Issue by MS07022** [Eficode/robotframework-imagehorizonlibrary#30]
Hi,

I'm getting this error while adding init_py file in eclipse, as python library. Please help me on this issue.

Thanks in Advance..!!!
![image](https://cloud.githubusercontent.com/assets/28750668/26143470/bc6c90de-3b02-11e7-917a-d6ac33971abc.png)

**Comment by Tattoo** [comment]
Why are you adding __init__.py in Eclipse in the first place? I do not understand why you would do this

**Comment by MS07022** [comment]
To use this library, we need to add init_py file in the eclipse, then only we can use the library.

**Comment by Tattoo** [comment]
The way you use libraries in Eclipse, as far as I know, is to make them available in PYTHONPATH

Please see documentation: http://www.pydev.org/manual_101_interpreter.html
