### ISSUE TITLE
Accessing library in Robot Framework's RIDE

### ISSUE THREAD

**Issue by aqin24** [Eficode/robotframework-imagehorizonlibrary#31]
I'm trying to use the Image Horizon Library on RIDE but it can't seem to access it and its keywords. When trying to import a library, it shows up as red.

**Comment by Tattoo** [comment]
What is the error message in RIDE console?

**Comment by Tattoo** [comment]
Closing since no new information. Please create a new one if this problem still persist and provide debug informationf rom RIDE's console
