### ISSUE TITLE
ImageNotFoundException on MacOS  (but image is on screen) 

### ISSUE THREAD

**Issue by BorisMolch** [eficode/robotframework-imagehorizonlibrary#34]
Just installed the library and giving it a go on MacOS 10.12
Using the keyword Click Image, I get an ImageNotFoundException 
Image is clearly on the screen.
The thing is I am getting the same result when the reference image is not even present in the image folder (when I manually place it somewhere else) or name it wrong in the robot script
Am I missing something ?
Thank You

**Comment by matejc** [comment]
Did you set reference_folder on import? Like so:
```
Library    ImageHorizonLibrary    ${CURDIR}${/}images
```

**Comment by Tattoo** [comment]
`InvalidImageException` comes when you are trying to refer to a reference image file that does not exist on the disk.

**Comment by Tattoo** [comment]
Closing since no new info. Please open a new issue if this occurs again.
