### ISSUE TITLE
Problem trying to execute atests

### ISSUE THREAD

**Issue by hernandik** [eficode/robotframework-imagehorizonlibrary#37]
I tried to execute atest windows_tests.robot, but I keep getting 

[ ERROR ] Error in file 'C:\Users\User\Desktop\robotframework-imagehorizonlibrary\tests\atest\windows_tests.robot': Importing test library 'ImageHorizo nLibrary' failed: SyntaxError: 'return' with argument inside generator (__init__.py, line 168)                                                          Traceback (most recent call last):                                                                                                                        File "c:\python27\lib\site-packages\ImageHorizonLibrary\__init__.py", line 8, in                                                                  import pyautogui as ag                                                                                                                                File "c:\python27\lib\site-packages\pyautogui\__init__.py", line 84, in                                                                           import pyscreeze                                                                                                                                    PYTHONPATH:
--

**Comment by hernandik** [comment]
I found the solution to this problem.
Running outside robot, the error message show that the problem is in the PyScreeze==0.1.20 python lib. Downgrading to 0.1.19 the problem does not happen.
Is possible that the lib pyautogui==0.9.42 should be downgraded too.
--



--

**Comment by matejc** [comment]
Tests have been rewritten, please track this PR: https://github.com/eficode/robotframework-imagehorizonlibrary/pull/46

**Comment by Tattoo** [comment]
Closing this issue since a) dependencies will be updated in the next release, b) this is pyscreeze issue, not IHL
