### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by gotcha1** [eficode/robotframework-imagehorizonlibrary#39]
Facing "TypeError: 'NoneType' object has no attribute '__getitem__' "when running below code:

*** Settings ***
Library  BuiltIn
Library  OperatingSystem
Library  Process
Library  AutoItLibrary
Library  Collections
Library  ImageHorizonLibrary  reference_folder=c:\\downloads

*** Test Case ***
Run Application
  App
*** KeyWords ***
App
  AutoItLibrary.Run  C:\\Downloads\\CinebenchR20\\app.exe
  Sleep  5s
  Locate  file
  Click Image  file
  Sleep  1s
  locate  selectall
  Click Image  selectall

Setup details:
Python v2.7
Pillow==2.9.0
PyAutoGUI==0.9.42
PyGetWindow==0.0.4
robotframework==3.1.2
robotframework-autoitlibrary==1.2.4
robotframework-imagehorizonlibrary==0.1

**Comment by Tattoo** [comment]
again, provide the full stacktrace. you are not even telling where (which keyword? or in import?) this fails

**Comment by gotcha1** [comment]
Robot framework log report has below error:
<img width="642" alt="log" src="https://user-images.githubusercontent.com/51114133/59668691-7f43c280-91eb-11e9-8bed-ca1190f29cf3.PNG">

Documentation: | Locate image on screen.
-- | --
20190618 13:19:02.972 / 20190618 13:19:04.209 / 00:00:01.237

FAIL | TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Tattoo** [comment]
It would be more helpful if you could just attach the log.html instead of screenshot...

**Comment by gotcha1** [comment]
> It would be more helpful if you could just attach the log.html instead of screenshot...


[log.zip](https://github.com/eficode/robotframework-imagehorizonlibrary/files/3300778/log.zip)

**Comment by gotcha1** [comment]
[log.zip](https://github.com/eficode/robotframework-imagehorizonlibrary/files/3304005/log.zip)

**Comment by gotcha1** [comment]
@Tattoo any update? Did you get a chance to look at the logs?

**Comment by KerbalSpaceFrontier** [comment]
Turns out the error is actually related to pyscreeze's locateCenterOnScreen() and center(coords). If you edit pyscreeze's __init__.py and change center(coords) to
`def center(coords):
    if coords is None:
        return coords
    else:
        return Point(coords[0] + int(coords[2] / 2), coords[1] + int(coords[3] / 2))`

then rerun the setup.py install it will now return None when the image isn't found. This will allow all of image horizon's errors to display properly.

There is an issue for this on pyscreeze's git page from May.

**Comment by matejc** [comment]
The OpenCV is merged to master branch, will make a release in upcoming days/weeks, I hope that it solves this issue also

**Comment by Tattoo** [comment]
Yes, the opencv support should alleviate problems. Closing this issue, if there are further problems please open a new ticket
