### ISSUE TITLE
Type With Keys Down doesn't work with Key.Shift + Key.End compination on windows

### ISSUE THREAD

**Issue by stade** [Eficode/robotframework-imagehorizonlibrary#4]
Can't select all rows in windows desktop application with code above:

Type With Keys Down     Key.End + Key.Shift

Os is windows 7 professional 32bit.
Default keyboard layout is finnish.

**Comment by suonto** [comment]
press_combination(*keys) is the intended method to press combinations
type_with_keys_down(text, *keys) toggles the specified keys down and types parameter text

Please confirm that this issue exists and if so, provide further information about it.

**Comment by suonto** [comment]
Closing, reopen if issue still exists.
