### ISSUE TITLE
Library should implement the confidence argument if opencv is installed

### ISSUE THREAD

**Issue by JonKoser** [eficode/robotframework-imagehorizonlibrary#41]
It would be great if we could implement the "confidence" parameter for pyautogui's screenshot functions. I've done this on my `feature/confidence_level` branch in [my fork of the repository](https://github.com/JonKoser/robotframework-imagehorizonlibrary). However, it is based off of my Python3 version of the library in my `feature/python3` branch.
My `integration` branch combines the two branches above. All unit and acceptance tests pass with python3.

**Comment by JonKoser** [comment]
PR #43 should do this.

**Comment by matejc** [comment]
Thanks! Merged.
