### ISSUE TITLE
Is it likely to consider improving the stability of the library?

### ISSUE THREAD

**Issue by fengnex** [eficode/robotframework-imagehorizonlibrary#50]
Maybe robotframework-SikuliLibrary is a good reference when it comes to a rich set of keywords and easy usage, which can be confirmed from the following URL:
https://github.com/rainmanwy/robotframework-SikuliLibrary

But robotframework-SikuliLibrary cannot identify the same images that are taken from ONE certain object but through different devices with different video cards. For example, a software logo will be displayed in a different size on different screens or different mobile phones and in such specific cases, robotframework-SikuliLibrary will fail to find the specified image, causing tests that actually already passed to get failed. This issue has a great negative impact on the practical application of similar libraries.

The above issue can be resolved with the help of OpenCV4Python and I hope to see the achievement of robotframework-imagehorizonlibrary in this aspect.

**Comment by Tattoo** [comment]
Sorry but I have hard time understanding are you asking a question, reporting a bug, or making a feature request. Could you please edit your issue so your intention would be more clear. If it's a bug or feature request, could you provide an example where the library fails, or how it could work.

**Comment by fengnex** [comment]
I am making a feature request in order to improve the success rate of finding an image from the screen.

I mean, there should be some improvements when recognizing an image from another one which contains a smaller or bigger image. You know, many libraries will fail to locate it in such circumstances since comparing images pixel by pixel is so popular, but these circumstances are quite frequent in our everyday work.

My suggestion is that gradually resizing the whole screen image within a certain span and then find the specified image from the resized one through OpenCV. The previous result which corresponds to the maximum similarity can be selected as the result of the whole operation, generating a more accurate finding, I believe.

**Comment by fengnex** [comment]
After dosing certain simple research on how the library recognizes one small image from the screen, I have found that it is the method called _locateAll_python in pyscreeze.py that actually does the job. 

The _locateAll_python method seems simply compares each value in the matrix of the to be funded image with corresponding data on the screen. A variable called foundMatch will be set as false to indicate that the find operation got failed. 

So, the combination of resizing the screen image and cv2's matchTemplate should work better. Also, I believe this solution should be much simpler when comparing with those codes in pyautogui.

**Comment by Tattoo** [comment]
@fengnex ,

Sorry to say, but we are not probably going to touch our library like `pyscreeze`, as it's outside of this projects. If there's some other dependency that results in less code for us to maintain, we will consider -- please open another issue or commit a PR for that. But right now, `pyautogui` offers the kind of API we want and works decently well.
