### ISSUE TITLE
can't integrate to Red...

### ISSUE THREAD

**Issue by jlmxyz** [Eficode/robotframework-imagehorizonlibrary#54]
I installed the lib using python -m pip install robotframework-imagehorizonlibrary
when I do a python -m pip freeze I get : robotframework-imagehorizonlibrary==1.0

now I created a resource file,
![image](https://user-images.githubusercontent.com/40383940/138877677-a0588a44-824a-4834-8e08-349a7dc2e220.png)

in red.xml file, it says it can't process the lib keyword because library specification was not generated 
![image](https://user-images.githubusercontent.com/40383940/138877510-47c6d420-a8a2-451a-8b0c-92e4338d3991.png)

```

>python -m robot.libdoc ImageHorizonLibrary ImageHorizonLibrary.libspec
Initializing test library 'ImageHorizonLibrary' with no arguments failed: NameError: global name 'ModuleNotFoundError' is not defined
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\ImageHorizonLibrary\__init__.py", line 149, in __init__
    self.has_cv = utils.has_cv()
  File "C:\Python27\lib\site-packages\ImageHorizonLibrary\utils.py", line 35, in has_cv
    except ModuleNotFoundError as err:

Try --help for usage information.

```

**Comment by Tattoo** [comment]
hello @jlmxyz ,

As specified in the README, ImageHorizonLibrary 1.0 requires Python 3.x version. You are apparently running Python 2.7, in other words, unsupported version of Python.

The previous version should probably still work with Python 2.7, which you can install with:
```bash
$ python -m pip install robotframework-imagehorizonlibrary==0.1
```
