### ISSUE TITLE
Acceptance tests do not work in Linux in CICD

### ISSUE THREAD

**Issue by Tattoo** [Eficode/robotframework-imagehorizonlibrary#55]
The Github Actions for Linux are failing: 

https://github.com/eficode/robotframework-imagehorizonlibrary/actions/runs/1428656401

Since the screenshots are blank, it's probably something to do with xvfb. Other users have reported that the errors are random.

**Comment by matejc** [comment]
@Tattoo I tested our hypothesis that Wayland is the fault, its not, at least not here, Xvfb creates non-privileged X11 server already on display 99 (in CICD) and on my Wayland infested Fedora 34, scrot works with that no-problem, but for me the tests still fail with same error message. What I did is:
```shell
export DISPLAY=:99
Xvfb :99 -screen 0 1024x768x24 -ac -noreset &
python tests/atest/run_tests.py
```
While this is running in one shell I have 10seconds of time to run in another terminal:
```shell
DISPLAY=:99 scrot
```
And it produces the screenshoot with the testing app, like it should

**Comment by Tattoo** [comment]
Thanks for the effort, @matejc !
