### ISSUE TITLE
"Does exist" returns always true

### ISSUE THREAD

**Issue by pajupaju** [Eficode/robotframework-imagehorizonlibrary#6]
"Does exist" passes every single time, even if the reference image is not visible on the screen.

Problem could be that "except" -part is never reached, because "return bool" is executed every single time:
            try:
                return bool(self._locate(reference_image, log_it=False))
            except ImageNotFoundException:
                return False

**Comment by suonto** [comment]
Can you describe the scenario further? I have tested on mac that _locate raises ImageNotFoundException if ag.locateCentorOnScreen returns None, with this code:
from ImageHorizonLibrary import ImageHorizonLibrary
lib = ImageHorizonLibrary(reference_folder='../tests/atest/reference_images/mac')
lib._locate('button_0')
At least try printing the return value of ag.locateCenterOnScreen.

**Comment by pajupaju** [comment]
Just try to use "does exist" with any image (that is not visible) on the screen and it will still "pass".

Locate (_locate) seems to work the way it should. So I don't know where the actual problem is.

**Comment by suonto** [comment]
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ImageHorizonLibrary import ImageHorizonLibrary
>>> lib = ImageHorizonLibrary('../tests/atest/reference_images/mac')
>>> print lib.does_exist('button_0')
False

**Comment by suonto** [comment]
Updated documentation.
