### ISSUE TITLE
pip install ImageHorizonLibrary-0.1-devel.zip command fails with pip 6.0.8 & win7 32bit

### ISSUE THREAD

**Issue by stade** [Eficode/robotframework-imagehorizonlibrary#7]
![pip_fails](https://cloud.githubusercontent.com/assets/1289784/11182988/bd481cb6-8c77-11e5-8b02-802901ccaa97.png)

This can be worked around by installing "image" package by running command:
"pip install image" before installing imagehorizon library.

**Comment by suonto** [comment]
Seems that pip install pyautogui has been deprecated. Updated README to fix this.
