### ISSUE TITLE
Dependency numpy must be pinned to 1.26.4

### ISSUE THREAD

**Issue by HelioGuilherme66** [Eficode/robotframework-imagehorizonlibrary#72]
I am not sure where the `numpy` dependency comes from, but recently ImageHorizonLibrary stopped working on my system

I solved by downgrading `numpy` to the last 1.x version, 1.26.4.

There should be a `numpy < 2.0.0` requisite in this project, or PIL, or pyautoit, or opencv-python, ...

Windows 10 Pro, x64, Python 3.9.7.
```
>pip show robotframework-ImageHorizonLibrary
Name: robotframework-imagehorizonlibrary
Version: 1.0
Summary: Cross-platform Robot Framework library for GUI automation based on image recognition
Home-page: https://github.com/Eficode/robotframework-imagehorizonlibrary
Author: Eficode Oy
Author-email: info@eficode.com
License: MIT
Location: c:\python39\lib\site-packages
Requires: pyautogui, robotframework
Required-by:
```

**Comment by Tattoo** [comment]
Testing this, neither ImageHorizonLibrary nor any upstream dependencies (Robot Framework & Pyautogui) result in numpy being installed. Thus, closing this issue.
