### ISSUE TITLE
Always print/log full reference image path when reference image is not found.

### ISSUE THREAD

**Issue by stade** [Eficode/robotframework-imagehorizonlibrary#8]
Some keywords do this but for example "wait for" doesn't. This feature would be really helpful to clear out situations where problems are caused by faulty imagepath when for example there is multiple coexisting imagehorizonlibrary imports with different reference image folders.

**Comment by suonto** [comment]
Fixed in commit 2d830dbbb59db74abf56a4b369a8f4df3366bca9
