### ISSUE TITLE
Capability to set the recognition to less than pixel perfect

### ISSUE THREAD

**Issue by failattu** [eficode/robotframework-imagehorizonlibrary#9]
We are currently facing a problem where we have windows server and windows 8 machine. Setting the windows machine to classic mode leaves the RGB values around 1-2% off which means the picture won't be recognized.

Solution would be to be able to give parameter like check with 90% detail etc.

**Comment by Tattoo** [comment]
@failattu this is now supported with #43 and will be part of the next release
